version: "3.9"

services:

  backend:
    build: .
    container_name: backend

  ai-service:
    image: python:3.11

    working_dir: /app

    volumes:
      - ./ai-service:/app

    command: >
      sh -c "
      pip install -r requirements.txt &&
      python app.py
      "

    ports:
      - "5001:5001"